---
version: 1

kind: experiment

framework: pytorch

build:
  image: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
  build_steps:
    - apt-get update
    - apt-get install build-essential git -y
    - pip install -r requirements.txt
      
environment:
  resources:
    cpu:
      requests: 1
      limits: 8
    memory:
      requests: 32768
      limits: 65536
    gpu:
      requests: 1
      limits: 1
#  node_selector:
#    gpuMemory: '12'

declarations:
  data_root: /data/CholecT50-challenge-train/pp2/tmh
  gpus: 1
  lr: 1e-6
  embed_dim: 1024

run:
  cmd: LOCAL_RANK=0 \
    CUDA_LAUNCH_BLOCKING=1 \
    WANDB_API_KEY=68baf49e41abf45f853f0296d1586f191ffd70ba \
    python train.py \
    --data_root {{ data_root }} \
    --gpus {{ gpus }} \
    --learning_rate {{ lr }} \
    --embed_dim {{ embed_dim }} \
    --reload_data \
    --on_cluster \
    --on_polyaxon